# -*- coding: utf-8 -*-
"""Multi-Agent System for Instagram Content Creation Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rdkp3GFSQMnWLQ_2SB4lvsv3GdJ1QEx5

# Multi-Agent System for Instagram Content Creation
Project Video Link: https://drive.google.com/file/d/1zokdSuslT_UlJbCCcRj4fEuuDS0xqOvz/view?usp=sharing

## 1. Install Dependencies
"""

# !pip install numpy==1.26.4 --force-reinstall

# Install required packages
!pip install -q crewai crewai_tools tavily-python langchain-openai langchain_community requests Pillow python-dotenv

import warnings
warnings.filterwarnings('ignore')

"""## 2. API Configuration"""

import os

# Set environment variables
os.environ["GITHUB_TOKEN"] = "GITHUB_TOKEN"
os.environ["TAVILY_API_KEY"] = "TAVILY_API_KEY"
os. environ["OPENAI_API_KEY"] = "OPENAI_API_KEY"
os.environ["OPENAI_API_BASE"] = "https://models.github.ai/inference"

print("API Keys configured successfully!")

"""## 3. Import Libraries & Setup"""

from crewai import Agent, Task, Crew, Process, LLM
from crewai.tools import tool
from tavily import TavilyClient
import requests
from PIL import Image
from io import BytesIO
from IPython.display import Image as IPImage, display

# Initialize Tavily
tavily_client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])

# Initialize LLM with GitHub Models
llm = LLM(
    model="gpt-4.1-mini",
    api_key=os.environ["GITHUB_TOKEN"],
    base_url="https://models.github.ai/inference"
)

print("Libraries imported and LLM configured!")

"""## 4. Define Tools"""

@tool("Tavily Web Research Tool")
def tavily_search(query: str) -> str:
    """
    Advanced web research using Tavily AI.
    Returns comprehensive results with AI-generated summary.
    """
    try:
        response = tavily_client.search(
            query=query,
            search_depth="advanced",
            max_results=5,
            include_answer=True
        )

        output = []

        # Add AI summary
        if response.get('answer'):
            output.append(f"**AI Summary:**\n{response['answer']}\n")

        # Add detailed sources
        output.append("**Detailed Sources:**\n")
        for i, result in enumerate(response.get('results', []), 1):
            output. append(
                f"**{i}. {result['title']}**\n"
                f"{result['content']}\n"
                f"Source: {result['url']}\n"
            )

        return "\n".join(output)

    except Exception as e:
        return f"Error during search: {str(e)}"

print("Tavily Research Tool created!")

def generate_image(prompt: str, filename: str) -> str:
    """
    Generate image using Pollinations AI
    """
    import urllib.parse

    # Encode prompt for URL
    encoded_prompt = urllib. parse.quote(prompt)

    # Pollinations API endpoint
    url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true&model=flux"

    try:
        print(f"Generating with Pollinations AI...")
        response = requests.get(url, timeout=60)

        if response.status_code == 200:
            img = Image.open(BytesIO(response.content))
            img.save(filename)
            return f"Image saved as {filename}"
        else:
            return f"Error {response.status_code}"

    except Exception as e:
        return f"Error: {str(e)}"

print("Image Generation Tool created!")

"""## 5. Create Agents"""

# Agent 1: Research Agent
research_agent = Agent(
    role='Senior Social Media Research Specialist',
    goal='Conduct comprehensive research using Tavily AI to find viral trends, statistics, and engaging insights for Instagram content',
    backstory="""You are an expert social media researcher with 10+ years of experience.
    You specialize in identifying viral content angles, trending topics, and data-driven
    insights that resonate with Instagram audiences.  You use advanced AI search tools
    to uncover the most engaging information.""",
    tools=[tavily_search],
    verbose=True,
    llm=llm
)

# Agent 2: Content Writer Agent
writer_agent = Agent(
    role='Expert Instagram Content Creator',
    goal='Write scroll-stopping Instagram captions that maximize engagement, saves, and shares',
    backstory="""You are a professional Instagram copywriter who has created viral
    content for accounts with millions of followers. You know exactly how to write
    hooks that stop the scroll, structure captions for mobile readability, and use
    strategic hashtags and CTAs to drive engagement.""",
    verbose=True,
    llm=llm
)

# Anent 3: Content Reviewer Agent
reviewer_agent = Agent(
    role='Senior Content Editor & Quality Assurance Specialist',
    goal='Review and optimize Instagram content for grammar, tone, clarity, and maximum engagement potential',
    backstory="""You are a meticulous content editor who has worked with top Instagram
    influencers and Fortune 500 brands. You ensure every caption is grammatically
    perfect, tonally consistent, and optimized for maximum engagement. Your edits
    consistently improve performance metrics.""",
    verbose=True,
    llm=llm
)

# Agent 4: Image Prompt Generator Agent
image_agent = Agent(
    role='Master AI Image Prompt Engineer',
    goal='Create highly detailed, optimized prompts that generate stunning Instagram-worthy visuals using Stable Diffusion',
    backstory="""You are a renowned AI prompt engineer specializing in text-to-image
    generation for social media. You have mastered Stable Diffusion and know exactly
    how to craft prompts that produce eye-catching, professional-quality images with
    perfect composition, lighting, and Instagram aesthetics.""",
    verbose=True,
    llm=llm
)

print("All 4 agents created successfully!")
print("1. Research Agent (Tavily)")
print("2. Writer Agent")
print("3. Reviewer Agent")
print("4. Image Prompt Agent")

"""## 6. Create Tasks"""

def create_tasks(topic: str):
    """
    Creates tasks for all 4 agents based on the topic.
    """

    # Task 1: Research
    task1 = Task(
        description=f"""
        Research the topic: '{topic}'

        Use Tavily search tool to find:
        1. Latest trends and developments (2024-2025)
        2.  Surprising statistics and data points
        3. Viral angles and engaging insights
        4. Expert opinions and quotes
        5. Common questions people are asking

        Focus on information that would resonate with Instagram audiences
        and drive high engagement.
        """,
        agent=research_agent,
        expected_output="Comprehensive research report with 5-7 key insights, statistics, viral angles, and credible sources."
    )

    # Task 2: Write Captions
    task2 = Task(
        description=f"""
        Based on the research, write TWO Instagram caption versions for '{topic}':

        **SHORT VERSION (10-15 words):**
        - Powerful hook (first line)
        - 2-3 key insights with strategic emojis
        - Strong call-to-action
        - 5-7 relevant hashtags

        **LONG VERSION (20-30 words):**
        - Compelling story-driven hook
        - Detailed insights from research
        - Strategic emoji placement
        - Engaging call-to-action
        - 7-12 strategic hashtags

        Both versions must be:
        - Conversational and authentic
        - Value-driven
        - Scroll-stopping
        - Designed to maximize engagement
        """,
        agent=writer_agent,
        expected_output="Two complete Instagram captions (short and long versions) with hashtags, emojis, and CTAs clearly labeled.",
        context=[task1]
    )

    # Task 3: Review & Optimize
    task3 = Task(
        description=f"""
        Review and optimize both Instagram caption versions.

        Check for:
        1. Grammar and spelling (zero errors required)
        2. Hook strength (rate 1-10 and improve if needed)
        3. Mobile readability (line breaks, spacing, emojis)
        4. Hashtag relevance and strategy
        5. CTA effectiveness
        6. Overall engagement potential

        Provide:
        - Polished, final versions of both captions and hashtags
        """,
        agent=reviewer_agent,
        expected_output="Two publication-ready Instagram captions with hashtags.",
        context=[task2]
    )

    # Task 4: Generate Image Prompts
    task4 = Task(
        description=f"""
        Create 3 detailed Stable Diffusion image prompts for '{topic}':

        **PROMPT 1 - PHOTOREALISTIC:**
        Professional photography style, 8k quality, realistic lighting, magazine-worthy

        **PROMPT 2 - CREATIVE/ARTISTIC:**
        Bold artistic style, vibrant colors, trending on artstation, eye-catching

        **PROMPT 3 - MINIMALIST:**
        Clean design, negative space, modern aesthetic, Instagram-ready

        Each prompt must include (60-100 words):
        - Subject and composition details
        - Lighting and color palette
        - Style and mood descriptors
        - Technical quality tags

        Optimize for Stable Diffusion XL and Instagram aesthetics.
        """,
        agent=image_agent,
        expected_output="Three complete, clearly labeled image generation prompts optimized for Stable Diffusion, ready to use immediately.",
        context=[task1, task3]
    )

    return [task1, task2, task3, task4]

print("Task creation function ready!")

"""## 7. Run Content Creation System"""

def run_content_creator(topic: str):
    """
    Executes the complete Instagram content creation workflow.
    """
    print(f"\n{"─"*200}")
    print(f"Instagram Content Creation Started...")
    print(f"{"─"*200}")
    print(f"\nTopic: {topic}\n")

    # Create tasks
    tasks = create_tasks(topic)

    # Create crew
    crew = Crew(
        agents=[research_agent, writer_agent, reviewer_agent, image_agent],
        tasks=tasks,
        process=Process.sequential,
        verbose=True
    )

    # Execute
    result = crew.kickoff()

    print(f"\n{"─"*200}")
    print("Content Creation Completed!")
    print(f"{"─"*200}\n")

    return {
        'topic': topic,
        'tasks': tasks,
        'result': result
    }

print("Execution function ready!")

"""## 8. Execute: Example 1"""

# Define your topic
Topic = "The Future of Electric Cars"

# Run the system
output = run_content_creator(Topic)

"""## 9. View Final Output"""

print("\n" + "─"*200)
print("Complete Instagram Content Package")
print("─"*200)
print(f"\nTopic: {output['topic']}\n")

tasks = output['tasks']

# Display each agent's output
print("\n" + "─"*200)
print("1. Research Report (Research Agent)")
print("─"*200 + "\n")
if hasattr(tasks[0], 'output'):
    print(tasks[0].output. raw)
else:
    print("Research output not available yet.")

print("\n" + "─"*200)
print("2. Instagram Captions - Short & Long (Writer Agent)")
print("─"*200+ "\n")
if hasattr(tasks[1], 'output'):
    print(tasks[1].output.raw)
else:
    print("Caption output not available yet.")

print("\n" + "─"*200)
print("3. Reviwed & Optimized Content (Reviewer Agent)")
print("─"*200 + "\n")
if hasattr(tasks[2], 'output'):
    print(tasks[2].output.raw)
else:
    print("Review output not available yet.")

print("\n" + "─"*200)
print("4. Image Generation Prompts (Image Prompt Agent)")
print("─"*200 + "\n")
if hasattr(tasks[3], 'output'):
    print(tasks[3].output.raw)
else:
    print("Image prompt output not available yet.")

print("\n" + "─"*200)

"""# 10. Complete Instagram Post Package"""

# Outputs (captions + prompts)
print("\n" + "─"*200)
print("Instagram Post Content")
print("─"*200 + "\n")
if hasattr(tasks[2], 'output'):
    print(tasks[2].output.raw)
else:
    print("Review output not available yet.")

print("\n" + "─"*200)
print("Image Generation Prompts (Image Prompt Agent)")
print("─"*200 + "\n")
if hasattr(tasks[3], 'output'):
    print(tasks[3].output.raw)
else:
    print("Image prompt output not available yet.")

print("\n" + "─"*200)

"""## 11. Generate Images"""

# Generate images
prompts = [
    f"Professional photography of {Topic}, modern urban setting, natural golden hour lighting, sleek electric vehicle, 8k uhd, photorealistic, sharp focus, instagram aesthetic, cinematic",

    f"Creative vibrant digital art of {Topic}, bold neon colors, futuristic cityscape, dynamic composition, trending on artstation, highly detailed, eye-catching, modern design",

    f"Minimalist clean design of {Topic}, white background, simple elegant composition, modern aesthetic, professional photography, centered, instagram ready, high quality"
]

print("\n" + "─"*200)
print("Generating Images (Pollinations AI)")
print("─"*200 + "\n")

images = []
styles = ['Photorealistic', 'Creative/Artistic', 'Minimalist']

for i, prompt in enumerate(prompts, 1):
    filename = f"instagram_image_{i}.jpg"

    print(f"\nImage {i}/3: {styles[i-1]}")
    print(f"Prompt: {prompt[:100]}...")

    status = generate_image(prompt, filename)
    print(f"{status}")

    if os.path. exists(filename):
        images. append(filename)
        print(f"Success")
    else:
        print(f"Failed")

print("\n" + "─"*200)

# Display generated images
if images:
    print("Generated Images:")
    print("─"*200 + "\n")

    for i, img in enumerate(images, 1):
        print(f"\nImage {i}: {styles[i-1]}")
        display(IPImage(filename=img))
        print()

    print(f"\nSuccessfully generated {len(images)}/3 images!")
else:
    print("No images generated.")